[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  nnoremap <expr> <silent> <C-]> execute('LspDefinition') =~ "not supported" ? "\<C-]>" : ":echo<cr>"
  nnoremap <silent> gn :LspNextError<cr>
  nnoremap <silent> gN :LspPreviousError<cr>

  nnoremap <silent> <leader>r     :LspReferences<cr>
  nnoremap <silent> <leader>h     :LspHover<cr>
  nnoremap <silent> <leader>d     :LspPeekDefinition<cr>
  nnoremap <silent> <leader><C-d> :LspDefinition<cr>
  nnoremap <silent> <leader>t     :LspPeekTypeDefinition<cr>
  nnoremap <silent> <leader><C-t> :LspTypeDefinition<cr>
  nnoremap <silent> <leader>i     :LspPeekImplementation<cr>
  nnoremap <silent> <leader><C-i> :LspImplementation<cr>

  " set updatetime=500
  " autocmd CursorHold * silent! LspHover

  let g:lsp_highlight_references_enabled = 1

  au User lsp_setup call lsp#register_server({
        \ 'name': 'ccls',
        \ 'cmd': {server_info->[expand('~/opt/ccls/bin/ccls')]},
        \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
        " \ 'root_uri': {server_info->lsp#utils#path_to_uri(system('git rev-parse --show-toplevel))},
        \ 'initialization_options': {},
        \ 'whitelist': ['c', 'cpp', 'cc'],
        \ })
'''

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
  vmap f gc
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  let g:tmux_navigator_no_mappings = 1
  nnoremap <silent> <C-[> :TmuxNavigateLeft<cr>
  nnoremap <silent> <C-q> :TmuxNavigateDown<cr>
  nnoremap <silent> <C-k> :TmuxNavigateUp<cr>
  nnoremap <silent> <C-s> :TmuxNavigateRight<cr>
'''

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'
hook_add = '''
  let g:ac_smooth_scroll_du_sleep_time_msec = 3
  let g:ac_smooth_scroll_fb_sleep_time_msec = 3
'''

#
# airline
#

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1

  " set color of 'base16_vim' theme for airline
  let g:base16_gui00 = "2A363E"
  let g:base16_gui01 = "2A363E"
  let g:base16_gui02 = "425059"
  let g:base16_gui03 = "585858"
  let g:base16_gui04 = "8F9E9A"
  let g:base16_gui05 = "C5C8C6"
  let g:base16_gui06 = "e8e8e8"
  let g:base16_gui07 = "f8f8f8"
  let g:base16_gui08 = "CC6666"
  let g:base16_gui09 = "dc9656"
  let g:base16_gui0A = "f7ca88"
  let g:base16_gui0B = "81A2BE"
  let g:base16_gui0C = "86c1b9"
  let g:base16_gui0D = "C48459"
  let g:base16_gui0E = "B294BB"
  let g:base16_gui0F = "a16946"
  let g:base16_cterm00 = "00"  " black
  let g:base16_cterm01 = "10"
  let g:base16_cterm02 = "11"
  let g:base16_cterm03 = "08"  " brblack
  let g:base16_cterm04 = "12"
  let g:base16_cterm05 = "07"  " white
  let g:base16_cterm06 = "13"
  let g:base16_cterm07 = "15"
  let g:base16_cterm08 = "01"  " red
  let g:base16_cterm09 = "09"
  let g:base16_cterm0A = "02"  " green
  let g:base16_cterm0B = "04"  " blue
  let g:base16_cterm0C = "06"  " cyan
  let g:base16_cterm0D = "03"  " yellow
  let g:base16_cterm0E = "05"  " magenta
  let g:base16_cterm0F = "14"
  let g:airline_base16_improved_contrast = 1

  let g:airline_powerline_fonts = 1
  let g:airline_theme = 'base16_vim'

  let g:airline_symbols = {}
  let g:airline_left_sep = '⮀'
  let g:airline_left_alt_sep = '⮁'
  let g:airline_right_sep = '⮂'
  let g:airline_right_alt_sep = '⮃'
  let g:airline_symbols.branch = '⭠'
  let g:airline_symbols.readonly = '⭤'
  let g:airline_symbols.linenr = '⭡'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#
# colorscheme
#

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  let g:hybrid_custom_term_colors = 1
  let g:hybrid_reduced_contrast = 1
'''

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'rakr/vim-one'

#
# carbonpaper.vim
#

[[plugins]]
repo = 's417-lama/carbonpaper.vim'
hook_add = '''
  let g:carbonpaper#colorscheme          = 'PaperColor'
  let g:carbonpaper#background           = 'light'
  let g:carbonpaper#set_background_color = 0
  " let g:carbonpaper#highlight_bold       = 1
'''

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-colorscheme-switcher'
depends = ['vim-misc']
