[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  nnoremap <expr> <silent> <C-]> execute('LspDefinition') =~ "not supported" ? "\<C-]>" : ":echo<cr>"
  nnoremap <silent> gn :LspNextDiagnostic<cr>
  nnoremap <silent> gN :LspPreviousDiagnostic<cr>

  nnoremap <silent> <leader>r     :LspReferences<cr>
  nnoremap <silent> <leader>h     :LspHover<cr>
  nnoremap <silent> <leader>d     :LspPeekDefinition<cr>
  nnoremap <silent> <leader><C-d> :LspDefinition<cr>
  nnoremap <silent> <leader>t     :LspPeekTypeDefinition<cr>
  nnoremap <silent> <leader><C-t> :LspTypeDefinition<cr>
  nnoremap <silent> <leader>i     :LspPeekImplementation<cr>
  nnoremap <silent> <leader><C-i> :LspImplementation<cr>

  " set updatetime=500
  " autocmd CursorHold * silent! LspHover

  let g:lsp_highlight_references_enabled = 1

  au User lsp_setup call lsp#register_server({
        \ 'name': 'ccls',
        \ 'cmd': {server_info->[expand('~/opt/ccls/bin/ccls')]},
        \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
        " \ 'root_uri': {server_info->lsp#utils#path_to_uri(system('git rev-parse --show-toplevel))},
        \ 'initialization_options': {'completion': {'detailedLabel': v:false}},
        \ 'whitelist': ['c', 'cpp', 'cc'],
        \ })

  au User lsp_setup call lsp#register_server({
        \ 'name': 'texlab',
        \ 'cmd': {server_info->[expand('~/opt/texlab/texlab')]},
        \ 'initialization_options': {},
        \ 'whitelist': ['tex', 'plaintex'],
        \ })
'''

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
  vmap f gc
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  let g:tmux_navigator_no_mappings = 1
  nnoremap <silent> <C-[> :TmuxNavigateLeft<cr>
  nnoremap <silent> <C-q> :TmuxNavigateDown<cr>
  nnoremap <silent> <C-k> :TmuxNavigateUp<cr>
  nnoremap <silent> <C-s> :TmuxNavigateRight<cr>
'''

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'
hook_add = '''
  let g:ac_smooth_scroll_du_sleep_time_msec = 3
  let g:ac_smooth_scroll_fb_sleep_time_msec = 3
'''

#
# lightline
#

[[plugins]]
repo = 's417-lama/base16-terminal-lightline.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set noshowmode
  let g:lightline = {
        \ 'colorscheme': 'base16_terminal',
        " \ 'separator': {'left': "", 'right': ""},
        " \ 'subseparator': {'left': "", 'right': ""},
        " \ 'separator': {'left': "", 'right': ""},
        " \ 'subseparator': {'left': "", 'right': ""},
        \ 'separator': {'left': "", 'right': ""},
        \ 'subseparator': {'left': "", 'right': ""},
        " \ 'separator': {'left': "", 'right': ""},
        " \ 'subseparator': {'left': "", 'right': ""},
        \ 'tabline_separator': {'left': "", 'right': ""},
        \ 'tabline_subseparator': {'left': "", 'right': ""},
        " \ 'separator': {'left': "", 'right': ""},
        " \ 'subseparator': {'left': "", 'right': ""},
        " \ 'subseparator': {'left': "", 'right': ""},
        \ }
'''

#
# colorscheme
#

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  let g:hybrid_custom_term_colors = 1
  " let g:hybrid_reduced_contrast = 1
'''

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'rakr/vim-one'

#
# carbonpaper.vim
#

[[plugins]]
repo = 's417-lama/carbonpaper.vim'
hook_add = '''
  let g:carbonpaper#colorscheme          = 'PaperColor'
  let g:carbonpaper#background           = 'light'
  let g:carbonpaper#set_background_color = 0
  " let g:carbonpaper#highlight_bold       = 1
'''

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-colorscheme-switcher'
depends = ['vim-misc']
