[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() . "\<cr>" : "\<cr>"
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  nnoremap <expr> <C-]> execute('LspPeekDefinition') =~ "not supported" ? "\<C-]>" : ":LspDefinition<cr>"
  nnoremap <silent> gn :LspNextDiagnostic<cr>
  nnoremap <silent> gN :LspPreviousDiagnostic<cr>

  nnoremap <silent> <leader>r     :LspReferences<cr>
  nnoremap <silent> <leader>h     :LspHover<cr>
  nnoremap <silent> <leader>d     :LspPeekDefinition<cr>
  nnoremap <silent> <leader><C-d> :LspDefinition<cr>
  nnoremap <silent> <leader>t     :LspPeekTypeDefinition<cr>
  nnoremap <silent> <leader><C-t> :LspTypeDefinition<cr>
  nnoremap <silent> <leader>i     :LspPeekImplementation<cr>
  nnoremap <silent> <leader><C-i> :LspImplementation<cr>

  let g:lsp_document_code_action_signs_enabled = 0

  " set updatetime=500
  " autocmd CursorHold * silent! LspHover
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings = {
        \   'clangd': {
        \     'args': ['--header-insertion=never']
        \   },
        \   'pylsp-all': {
        \     'workspace_config': {
        \       'pylsp': {
        \         'plugins': {
        \           'pycodestyle': {'enabled': v:false},
        \           'mccabe': {'enabled': v:false},
        \         }
        \       }
        \     }
        \   },
        \ }
'''

[[plugins]]
repo = 'yssl/QFEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
  vmap <space> gc
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  let g:tmux_navigator_no_mappings = 1
  nnoremap <silent> <C-[> :TmuxNavigateLeft<cr>
  nnoremap <silent> <C-q> :TmuxNavigateDown<cr>
  nnoremap <silent> <C-k> :TmuxNavigateUp<cr>
  nnoremap <silent> <C-s> :TmuxNavigateRight<cr>
'''

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'
hook_add = '''
  let g:ac_smooth_scroll_du_sleep_time_msec = 3
  let g:ac_smooth_scroll_fb_sleep_time_msec = 3
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
  " Markdown can be easily gets wrong syntax highlight
  au BufEnter *.md,*.markdown syn sync fromstart
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_folding_style_pythonic = 1
  let g:vim_markdown_strikethrough = 1
  let g:vim_markdown_new_list_item_indent = 0
  let g:vim_markdown_toc_autofit = 1
'''

[[plugins]]
repo = 'qnighy/satysfi.vim'

#
# lightline
#

[[plugins]]
repo = 's417-lama/base16-terminal-lightline.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set noshowmode
  let g:lightline = {
        \ 'colorscheme': 'base16_terminal',
        \ 'separator': {'left': "", 'right': ""},
        \ 'subseparator': {'left': "", 'right': ""},
        \ 'tabline_separator': {'left': "", 'right': ""},
        \ 'tabline_subseparator': {'left': "", 'right': ""},
        \ }
  " let g:lightline = {
  "       \ 'colorscheme': 'base16_terminal',
  "       \ 'separator': {'left': "", 'right': ""},
  "       \ 'subseparator': {'left': "", 'right': ""},
  "       \ 'separator': {'left': "", 'right': ""},
  "       \ 'subseparator': {'left': "", 'right': ""},
  "       \ 'separator': {'left': "", 'right': ""},
  "       \ 'subseparator': {'left': "", 'right': ""},
  "       \ 'separator': {'left': "", 'right': ""},
  "       \ 'subseparator': {'left': "", 'right': ""},
  "       \ 'tabline_separator': {'left': "", 'right': ""},
  "       \ 'tabline_subseparator': {'left': "", 'right': ""},
  "       \ 'separator': {'left': "", 'right': ""},
  "       \ 'subseparator': {'left': "", 'right': ""},
  "       \ 'subseparator': {'left': "", 'right': ""},
  "       \ }
'''

#
# colorscheme
#

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  let g:hybrid_custom_term_colors = 1
  " let g:hybrid_reduced_contrast = 1
'''

[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'rakr/vim-one'

#
# carbonpaper.vim
#

[[plugins]]
repo = 's417-lama/carbonpaper.vim'
hook_add = '''
  let g:carbonpaper#colorscheme          = 'PaperColor'
  let g:carbonpaper#background           = 'light'
  let g:carbonpaper#set_background_color = 0
  " let g:carbonpaper#highlight_bold       = 1
'''

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-colorscheme-switcher'
depends = ['vim-misc']
